"""Initial migration

Revision ID: ad1885ab2beb
Revises: c2f3a0649359
Create Date: 2025-03-27 22:42:06.208405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1885ab2beb'
down_revision = 'c2f3a0649359'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
